#...............................................................................
#
#  This file is part of the Doxyrest toolkit.
#
#  Doxyrest is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/doxyrest/license.txt
#
#...............................................................................

dist:     trusty
sudo:     required
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - secure: fAr3FXUEmF/Vx2lUsHJrgqBW4ohDytUPw3VFrvdQLUzXekET5lhtwgN/kM1mCFUrMqKloazcAZVGaMJ8IxFRkxhJPjZ9v6Lo+8vkGkna80lx+W9+cAO5yEtoMBwl+hL7dClSfpwwIJAWkwZyD/Y85tKHhReHE/nx7MIl0rLdHREMdirERUxvSFuoOTuPv/PD+neNBQi3ZxHGjzTcUjsSEAfJl2q+WE8Vw3bUNwb/zDRovodAnNCHvyXwWHyyfwomnUTSRFhiw+GSpv4lvHQ60Vt4SumTbOvJ0xztVHSIhqPjkHKgran72Y/U7Lr2IRuBiQ4BbNadCpWk8WwH6B/UabEdEjqBjK6+X3xMB6qEOFzbU3iezcmMX+k24NAOAb8/MmFgPFO3QnGxeqqA2zObT+EL921aWHKui+9QugvI4FUVZwoTNPwaTRNGgHCPfYJ45qBB+wvC+5A33RWuuycdWx+nxum/KUTPvEzHkFFC5WngjT//wFmqsM+ryQsTBGiukY0fxdIKaaKdfYX8keZcHxI+W699mfpaQ35sgBzMdwRcoBcsI1aLoSEM4vyYnBhASXW7my4S9baHPL/wfb3lqDZA+IpFOHa9U+34mh1B48GIgQ2k9b8/uBmf5RLW2mxbtHuL9xO/nvzHxRabkr7iCCxgOtF/ilXpfo04MarNXIs=

    matrix:
        - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
        - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source ci/travis/set-env.sh
    - bash ci/travis/install-$TRAVIS_OS_NAME.sh
    - git clone --depth 1 https://github.com/vovkos/axl

script:
    - bash -e ci/travis/build.sh

notifications:
    webhooks:
        on_success: always
        on_failure: never
        on_error:   never
        on_cancel:  never

        urls:
            - http://jancy.org:5005/travis-ci

deploy:
    -   provider:      pages
        skip_cleanup:  true
        local_dir:     build/doc/html
        github_token:  $GITHUB_TOKEN

        on:
            branch:    master
            condition: $BUILD_DOC == ON

    -   provider:     releases
        file:         $DOXYREST_TAR

        skip_cleanup: true
        overwrite:    true

        api_key:
            secure:   oqX62d80KxTBwPMQJqEgFR/KXS1OCnvx1cTIwo7lwyYsbCi5+yuUTo/5ly10lF0p1e6N1rgNNHE2YRi7U8j8I2OPE93Vh/hWWD1AioZodEnenN96/jbI5X+mhfk9bkm1QEzwtkto3Ltm892QtfnwZtqsJd7Y7gWmGYmDPJGgtoYJWwZDO4AVPZy0nKzI1nI9AghwpBza9P/DUHlP+wA2hCmghlUsosD9u7JACuEtIvezEwn9tyyaR1SLSHVXyR9BCXQoHG7YZAIwBRbkNfKcUNqU410XIDvuIfSNggrOzRHKd4SN4cwQmfXgrvsma2iQSwJ2zkUkd/Kt6BU0Id2WzMPt8rxFhug4oiS/BsQhn/zUud5vTsxKrL+9bLXDjOcAmb2tYauF23Jg9K6u92Hn2xk15CK48VPtPkF1IDFjN6AL6FYhGHRPnrG/cw8qvSVKPUgy8ZHJcfjMGT9Oh/wag4MbSWU5CUAr3Yne88l7Vz4xCKB1cRBLligwK1wOf++7BKSu7+Z6Ud4LtFzhi7SYZBZOZCvNArrGAr0I0+2TIDLA4MRfTogo2sZaEIbyPN2zJidNaJ2kPG96C+j34dr9vMpiGITGZOnWfJP5/vtcxcqGtDcx7T08HQH8ZFa5LtjKCpgvcRHlxfwtG70RkKmn/o4JsQFgVe6n5g+p3rBdRr0=

        on:
            branch:    master
            tags:      true
            condition: $BUILD_PACKAGE == ON
